<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="BYODIIcU3lIgowY" failures="1" tests="1" name="Multis_Order_4" time="0.088" errors="0" timestamp="2023-07-24T22:47:30 IST">
  <testcase classname="WMS_Mult_Ord_Batch_4.WMS_Multis_Gift_Wrap" name="orderAllocation" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.io.FileNotFoundException: C:\Users\bhn\OneDrive - Levi Strauss &amp;amp; Co\Desktop\WMS_Henderson\WMS_Henderson\src\WMS_TestData_Secound.xlsx (The process cannot access the file because it is being used by another process)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\bhn\OneDrive - Levi Strauss & Co\Desktop\WMS_Henderson\WMS_Henderson\src\WMS_TestData_Secound.xlsx (The process cannot access the file because it is being used by another process)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.FileNotFoundException: C:\Users\bhn\OneDrive - Levi Strauss & Co\Desktop\WMS_Henderson\WMS_Henderson\src\WMS_TestData_Secound.xlsx (The process cannot access the file because it is being used by another process)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at resources.DataProviders.Multis_GiftWrap(DataProviders.java:823)
... 19 more
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- orderAllocation -->
</testsuite> <!-- Multis_Order_4 -->
